# Generated by Django 5.1.5 on 2025-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Conductor', 'Conductor'), ('Orchestra', 'Orchestra'), ('Ensemble', 'Ensemble'), ('Choir', 'Choir'), ('Piano', 'Piano'), ('Violin', 'Violin'), ('Cello', 'Cello'), ('Viola', 'Viola'), ('Double Bass', 'Double Bass'), ('Flute', 'Flute')], max_length=255)),
            ],
        ),
    ]
