# Generated by Django 5.1.5 on 2025-02-06 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_performer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_no', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.composer')),
            ],
        ),
    ]
