# Generated by Django 5.1.5 on 2025-02-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_work'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('composer', 'work_no'), name='unique_composer_work_no'),
        ),
    ]
