# Generated by Django 5.1.5 on 2025-02-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_work_unique_composer_work_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['composer', 'work_no']},
        ),
        migrations.AlterField(
            model_name='composer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
