# Generated by Django 5.1.5 on 2025-02-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_recording"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("recordings", models.ManyToManyField(blank=True, to="api.recording")),
                ("covers", models.ManyToManyField(blank=True, to="api.cover")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
